apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: tutorial-pipeline-run-1
  namespace: tekton
spec:
  pipelineRef:
    name: tutorial-pipeline
  serviceAccount: build-robot-git-ssh
  resources:
    - name: source-repo
      resourceRef:
        name: ${RESOURCE_NAME}
  params:
    - name: files
      value: ${FILES}